volumes:
  chroma-data:

services:
  chroma:
    image: chromadb/chroma:1.3.7
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
